language g0

# Configuration fixture for the Rust CLI test suite.
# Do not edit this file for manual development preferences; use dev.g or
# GLAS_CONF instead. Tests depend on the exact values below.

object conf.env

extend conf.env with
  hello_message = "Hello from unit_tests conf.env!"
